services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: "always"
    environment:
      - SECRET=${NESTJS_SECRET}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DB}
      - PORT=${NESTJS_PORT}
    ports:
      - "${NESTJS_PORT}:${NESTJS_PORT}"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: "always"
    environment:
      - BACKEND_HOST=${NESTJS_URL}
      - PORT=${NEXTJS_PORT}
    ports:
      - "${NEXTJS_PORT}:${NEXTJS_PORT}"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      # - ./frontend/.env.local:/app/.env.local
    depends_on:
      - backend
    networks:
      - my_network

  db:
    image: mysql
    container_name: db
    restart: "always"
    environment:
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
